coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 80
        threshold: 2
        paths:
          - "pages"
          - "components"
    patch:
      default:
        target: 80
