version: 2.1
orbs:
  cypress: cypress-io/cypress@3 # Cypress orb를 사용

jobs:
  test:
    docker:
      - image: cypress/included:10.0.0 # Cypress가 포함된 Docker 이미지
    steps:
      - checkout # 코드를 체크아웃합니다.
      - run:
          name: Install dependencies
          command: npm ci # 의존성 설치
      - run:
          name: Start application
          command: npm run start & # 백그라운드로 서버 시작
      - cypress/run:
          start: npm run start # 수정된 부분: Cypress가 서버 시작 명령을 기다리도록 수정

workflows:
  version: 2
  build:
    jobs:
      - test # test job을 워크플로우에 추가
