name: Build, Test, and Upload Coverage

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "main"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20]

    steps:
      # 1. 레포지토리 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Node.js 설정
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # 3. 의존성 설치
      - name: Install dependencies
        run: npm install

      # 4. Jest를 이용한 테스트 및 커버리지 리포트 생성
      - name: Run tests and generate coverage
        run: npm test -- --coverage

      # 5. Codecov에 커버리지 리포트 업로드
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # Codecov 토큰
          files: ./coverage/lcov.info # Jest에서 생성된 커버리지 파일
          flags: unittests
          fail_ci_if_error: true
